### ISSUE TITLE
There isn't a channel restriction for the say command.

### ISSUE THREAD

**Issue by GlowingRain** [GlowingRain/aquila-akairo#1]
https://github.com/GlowingRain/aquila-akairo/blob/f9e7c396fe3da47d2185c0d8fb0f33599d153294/src/commands/diversi%C3%B3n/say.js#L5-L22

Add channel restriction.

**Comment by TheDan439** [comment]
F

**Comment by GlowingRain** [comment]
It fucking breaks the bot if done in a DM

**Comment by GlowingRain** [comment]
Fixed with commit 04c2d70667d9c1c4f1c059e05fba0195000d1722
